services:
  kafka:
    extends:
      file: compose.yaml
      service: kafka

  registry:
    extends:
      file: compose.yaml
      service: registry

  jaws:
    extends:
      file: compose.yaml
      service: jaws
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - LOGLEVEL=DEBUG
      - ALARM_LOCATIONS=/data/locations
      - ALARM_SYSTEMS=/data/systems
      - ALARM_ACTIONS=/data/actions
      - ALARMS=/data/alarms
      #- ALARMS=https://raw.githubusercontent.com/JeffersonLab/alarms/main/instances
      #- ALARMS_URL_CSV=aperture,bcm,beamdump,bels,blm,box,bpm,camac,crates,cryo,dempow,gun,harp,helicity,ioc,ion,laser,lcw,misc,mo,odh,radcon,rf,rfsep,trim,vacuum
      - ALARM_OVERRIDES=/data/overrides
      #- ALARM_OVERRIDES=https://raw.githubusercontent.com/JeffersonLab/alarms/main/overrides
    volumes:
      - ./container/app/example-data:/data
      - ./container/app/container-entrypoint.sh:/container-entrypoint.sh