services:
  kafka:
    extends:
      file: docker-compose.yml
      service: kafka

  registry:
    extends:
      file: docker-compose.yml
      service: registry

  jaws:
    extends:
      file: docker-compose.yml
      service: jaws
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - LOGLEVEL=DEBUG
      - ALARM_LOCATIONS=/data/locations
      - ALARM_CATEGORIES=/data/categories
      - ALARM_CLASSES=/data/classes
      #- ALARM_INSTANCES=/data/instances
      - ALARM_INSTANCES=https://raw.githubusercontent.com/JeffersonLab/alarms/main/instances
      - ALARM_INSTANCES_URL_CSV=aperture,bcm,beamdump,bels,blm,box,bpm,camac,crates,cryo,dempow,gun,harp,helicity,ioc,ion,laser,lcw,misc,mo,odh,radcon,rf,rfsep,trim,vacuum
    volumes:
      - ./docker/app/example-data:/data
      - ./docker/app/docker-entrypoint.sh:/docker-entrypoint.sh