services:
  cli:
    image: jeffersonlab/jaws-libp:latest
    environment:
      - ALARM_LOCATIONS=INJ|CEBAF,NL|CEBAF,SL|CEBAF,CEBAF|
      - ALARM_SYSTEMS=Vacuum|VacGuys,RF|RfGuys,RADCON|RadGuys
      - ALARM_ACTIONS=base|RF|P1_MINOR|Timely operator action required|Call expert|True|False|10|10
      - ALARMS=alarm1|base|channel1|INJ|||command1,alarm2|base|channel2|NL||alarm1|command2,alarm3|special||INJ|||command3