services:
  jaws:
    image: jeffersonlab/jaws-libp:4.8.3
    environment:
      - ALARM_LOCATIONS=INJ|CEBAF,NL|CEBAF,SL|CEBAF,CEBAF|
      - ALARM_CATEGORIES=Vacuum,RF,RADCON
      - ALARM_CLASSES=base|RF|P4.8.3_MINOR|Timely operator action required|Call expert|helpdesk|True|False|10|10
      - ALARM_INSTANCES=alarm4.8.3|base|channel1|INJ||command1,alarm2|base|channel2|NL|alarm1|command2,alarm3|special||INJ||command3