services:
  kafka:
    extends:
      file: deps.yml
      service: kafka

  registry:
    extends:
      file: deps.yml
      service: registry

  jaws:
    tty: true
    stdin_open: true
    hostname: jaws
    container_name: jaws
    healthcheck:
      test: test $(list_schemas | wc -l) -gt 20
      start_period: 20s
      start_interval: 10s
      interval: 10s
      timeout: 10s
      retries: 5
    depends_on:
      registry:
        condition: service_healthy
    environment:
      - TZ=America/New_York
      - BOOTSTRAP_SERVERS=kafka:9092
      - SCHEMA_REGISTRY=http://registry:8081