services:
  zookeeper:
    extends:
      file: deps.yml
      service: zookeeper

  kafka:
    extends:
      file: deps.yml
      service: kafka

  registry:
    extends:
      file: deps.yml
      service: registry

  jaws-libp:
    tty: true
    stdin_open: true
    hostname: jaws-libp
    container_name: jaws-libp
    depends_on:
      - zookeeper
      - kafka
      - registry
    environment:
      TZ: "America/New_York"
      BOOTSTRAP_SERVERS: "kafka:9092"
      SCHEMA_REGISTRY: "http://registry:8081"