name: CD

on:
  push:
    branches: [ main ]
    paths:
      - 'VERSION'

jobs:
  release:
    uses: jeffersonlab/python-workflows/.github/workflows/gh-release.yml@v1

  artifact_publish:
    needs:
      - release
    uses: jeffersonlab/python-workflows/.github/workflows/pypi-publish.yml@v1
    secrets: inherit

  docs_publish:
    needs:
      - release
    uses: jeffersonlab/python-workflows/.github/workflows/gh-pages-publish.yml@v1
    with:
      semvertag: ${{ needs.release.outputs.semvertag }}
    secrets: inherit

  docker_publish:
    needs:
      - release
    uses: jeffersonlab/container-workflows/.github/workflows/docker-publish.yaml@v2
    with:
      semvertag: ${{ needs.release.outputs.semvertag }}
    secrets: inherit