name: CD

on:
  push:
    branches: [ main ]
    paths:
      - 'VERSION'

jobs:
  release:
    uses: jeffersonlab/python-workflows/.github/workflows/gh-release.yaml@v2

  artifact_publish:
    needs:
      - release
    uses: jeffersonlab/python-workflows/.github/workflows/pypi-publish.yaml@v2

  docs_publish:
    needs:
      - release
    uses: jeffersonlab/python-workflows/.github/workflows/gh-pages-publish.yaml@v2
    with:
      semvertag: ${{ needs.release.outputs.semvertag }}

  docker_publish:
    needs:
      - release
    uses: jeffersonlab/container-workflows/.github/workflows/docker-publish.yaml@v2
    with:
      semvertag: ${{ needs.release.outputs.semvertag }}
    secrets: inherit