name: CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'VERSION'
    tags-ignore:
      - "v*.*.*"
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  unit:
    uses: jeffersonlab/python-workflows/.github/workflows/unit-ci.yaml@v2

  integration:
    needs:
      - unit
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev]
    - name: Start containers
      run: docker compose -f deps.yaml up -d
    - name: Wait for containers to settle
      run: docker exec -i kafka bash -c "sleep 20"
    - name: Test
      run: |
        pytest tests/integration
    - name: Stop containers
      if: always()
      run: docker compose -f deps.yaml down
