name: Publish to gh-pages

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    concurrency:
      group: docs-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
      - name: Build
        run: |
          python -m build
          sphinx-build -b html docsrc/source build/docs
      - name: Deploy Docs
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build/docs
          target-folder: ${{ github.ref_name }}